 const userData=[
    {
        id:1,
        name:'Abdullah',
        district:'pabna',
        image:'./images/image1.jpg',
        mobile:'01744506815'
    },
    {
        id:2,
        name:'Raihan',
        district:'jessore',
        image:'./images/image2.jpg',
        mobile:'017408678'
    },
    {
        id:3,
        name:'Fahim',
        district:'pabna',
        image:'./images/image3.jpg',
        mobile:'01740668'
    },
    {
        id:4,
        name:'Toru',
        district:'chuadanga',
        image:'./images/image4.jpg',
        mobile:'01740668'
    },
    {
        id:5,
        name:'Kamrul',
        district:'Dhaka',
        image:'./images/image5.jpg',
        mobile:'01744506815'
    },
    {
        id:6,
        name:'Sayem',
        district:'khulna',
        image:'./images/image6.jpg',
        mobile:'017408678'
    },
    {
        id:7,
        name:'Raju',
        district:'khulna',
        image:'./images/image7.jpg',
        mobile:'01740668'
    },
    {
        id:8,
        name:'Rofiq',
        district:'chuadanga',
        image:'./images/image8.jpg',
        mobile:'01740668'
    }

]

export default userData